name: movieapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  
  provider: ^6.1.2
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.0.0
  build_runner: ^2.0.0
  analyzer: ^4.7.0



flutter:
  uses-material-design: true
  assets:
   - assets/splash/
   - .env



flutter_native_splash:
  color: "#242A32"
  image: assets/splash/splash.png
  android_12:
    image: assets/splash/splash.png
  android: true
  ios: true
